namespace: "dimagi"
name: "commcare_logstash"
version: "0.9.4"
readme: "README.md"
authors:
    - "rkumar@dimagi.com"
    - "skelly@dimagi.com"
repository: "https://www.github.com/dimagi/commcare-logstash"
