namespace: "dimagi"
name: "commcare-logstash"
version: "1.0.0"
readme: "README.md"
authors:
    - "rkumar@dimagi.com"
    - "skelly@dimagi.com"
repository: "https://www.github.com/dimagi/commcare-logstash"
